### ISSUE TITLE
Convert shell scripts to python

### ISSUE THREAD

**Issue by nmoinvaz** [neurolabusc/pigz-bench#3]
This is a feature request to convert the shell scripts to python which is more cross-platform scripting.

**Comment by neurolabusc** [comment]
@nmoinvaz please try this [Python port](https://github.com/neurolabusc/pigz-bench-python). At the moment, all gz compressors are tested at levels 2..9. I will change this to 1..9 once your [pull requests](https://github.com/zlib-ng/zlib-ng/issues/536) are implemented. I am not very experienced with Python, so feel free to improve on these scripts. I would rather make this a separate project as the Python requires a lot of dependencies that make rapid testing on servers a challenge. The Python code is tested on Linux, MacOS and Windows, so it does provide better cross-platform support. It also integrates plotting for systems that support graphical output, and saves data for plotting in pickle format for systems without a graphical display.

**Comment by nmoinvaz** [comment]
@neurolabusc wow thanks for implementing some of the changes! I have been using the pigz-bench extensively. 

One thing I have noticed, after you added the `ms` column, that some of the results were dependent upon the disk I/O. For example, in some of my tests zlib-ng and cloudflare were near the same when you factor in the change in `ms`. I am wondering if it is possible to load the entire test file in memory and then performing the test. The `pigz` app might then print out some stats about time spent. I'm not sure if it is overkill or not. What I have been doing in the mean time is just running `pigz-bench` off a RAM drive. Now that you converted it to python I think I will see IO be less of an impact. Before I was running the `pigz-bench` on Windows Subsystem for Linux. What do you think? How are you running it?

**Comment by neurolabusc** [comment]
@nmoinvaz I am not sure there is a cross-platform way to set up a RAM disk in Python. Also, I think many users would want to see the real world performance of writing to a real disk, as some tools could conceivably do a better job of reading/writing blocks efficiently. On the other hand, due to effects like disk caching it is possible that the first tool that is run is disadvantaged against subsequent tools (and it might benefit from Turbo modes if the CPU is able to clock higher for the first few seconds). I note that [zlib-bench](https://github.com/jsnell/zlib-bench/blob/master/bench.pl) conducts a `warmup run` that attempts to counter these effects. One could do something similar.

By the way, with the Python scripts you can request to repeat the benchmark for a desired number of runs using the `repeats` parameter. This should minimize effects and has the benefit of averaging across any variation due to the system doing other tasks. For example, [d_speed_size.py](https://github.com/neurolabusc/pigz-bench-python/blob/master/d_speed_size.py):

    """Compare speed and size for different compression tools
    Parameters
    ----------
    indir : str
        folder with files to compress (default './corpus')
    repeats : int
     how many times is each file compressed. More (default 1)    
    """
